[project]
authors = ["danielnachun <daniel.nachun@gmail.com>"]
channels = ["dnachun", "conda-forge", "bioconda"]
description = "Add a short description here"
name = "code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gtex-pipeline-rnaseq = ">=gtex_v8,<1a"
picard = "2.27.1.*"
star = "2.7.11b.*"
rsem = "1.3.3.*"
samtools = "1.19.2.*"

[system-requirements]
linux = "3.10"
libc = "2.17"
