[project]
authors = ["danielnachun <daniel.nachun@gmail.com>"]
channels = ["dnachun", "conda-forge", "bioconda"]
description = "Add a short description here"
name = "code"
platforms = ["linux-64"]
version = "0.1.0"

[feature.realignbam.dependencies]
bamsync = "gtex_v10.*"
gtex-pipeline-rnaseq = "gtex_v10.*"
picard = "2.27.1.*"
star = "2.7.11b.*"
rsem = "1.3.3.*"
samtools = "*"

[feature.quantifybam.dependencies]
gtex-pipeline-rnaseq = "gtex_v10.*"
gtex-pipeline-qtl = "gtex_v10.*"
bedtools = "2.31.1.*"
gatk4 = "*"
libboost = "1.85"
kent-tools = "*"
regtools = "*"
rnaseqc = "2.4.2.*"

[system-requirements]
linux = "3.10"
libc = "2.17"

[environments]
realignbam = ["realignbam"]
quantifybam = ["quantifybam"]
