[project]
authors = ["danielnachun <daniel.nachun@gmail.com>"]
channels = ["dnachun", "conda-forge", "bioconda"]
description = "Add a short description here"
name = "code"
platforms = ["linux-64"]
version = "0.1.0"

[feature.extractvcf.dependencies]
bcftools = "1.15.*"
samtools = "1.21.*"

[feature.realignbam.dependencies]
bamsync = "gtex_v10.*"
gtex-pipeline-rnaseq = "gtex_v10.*"
picard = "2.27.1.*"
star = "2.7.11b.*"
rsem = "1.3.3.*"
samtools = "1.21.*"

[feature.calledsites.dependencies]
python = "2.7.*"
sprint = "0.1.8.*"
bwa = "0.7.12.*"
samtools = "1.2.*"
fastp="1.0.*"

[feature.quantifybam.dependencies]
gtex-pipeline-rnaseq = "gtex_v10.*"
gtex-pipeline-qtl = "gtex_v10.*"
bedtools = "2.31.1.*"
gatk4 = "4.6.*"
kent-tools = "472.*"
regtools = "1.0.*"
rnaseqc = "2.4.2.*"
samtools = "1.21.*"
ipafinder = "1.0.*"
bioconductor-fraser = "2.2.*"
r-argparser = "0.7.*"
r-readr = "2.1.*"
r-biocmanager = "1.30.*"
reditools3 = "3.4.*"
subread="2.1.1.*"

[feature.runphaser.dependencies]
gtex-pipeline-phaser = "gtex_v10.*"

[feature.runmutect.dependencies]
gatk4 = "4.6.*"
bcftools = "1.15.*"


[feature.pecotmr.dependencies]
python = "3.12.*"
pandas = "2.3.*"
tqdm = "4.67.*"
r-pecotmr = "0.3.16.*"
r-argparser = "0.7.*"
r-readr = "2.1.*"
r-biocmanager = "1.30.*"
r-colocboost = "1.0.4*"
tabix = "1.11.*"

[feature.pecotmr-dev.dependencies]
python = "3.12.*"
pandas = "2.3.*"
tqdm = "4.67.*"
r-pecotmr = "0.3.16.*"
r-devtools="2.4.5*"
r-argparser = "0.7.*"
r-readr = "2.1.*"
r-biocmanager = "1.30.*"
r-colocboost = "1.0.4*"
tabix = "1.11.*"

[feature.plink.dependencies]
plink = "1.90b6.12.*"


[system-requirements]
linux = "3.10"
libc = "2.17"

[environments]
extractvcf = ["extractvcf"]
realignbam = ["realignbam"]
calledsites = ["calledsites"]
quantifybam = ["quantifybam"]
runphaser = ["runphaser"]
runmutect = ["runmutect"]
pecotmr = ["pecotmr"]
pecotmr-dev = ["pecotmr-dev"]
plink = ["plink"]